#!/usr/bin/env python3
"""PreCompact snapshot generator for Claude Code hook."""

import json
import os
import sys
from datetime import datetime
from pathlib import Path


DEFAULT_MEMORY_DIR = os.path.expanduser("~/.claude/memory")
DEFAULT_OUTPUT_DIR = os.path.join(DEFAULT_MEMORY_DIR, "compact", "precompact")


def read_stdin():
    """Read JSON from stdin."""
    try:
        return json.loads(sys.stdin.read())
    except json.JSONDecodeError:
        return None


def format_timestamp():
    """Format current timestamp for filename."""
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def generate_snapshot_content(payload: dict) -> list:
    """Generate snapshot content lines from payload."""
    lines = []

    # Basic session info
    lines.append("# PreCompact Snapshot\n")

    # Transcript path
    transcript_path = payload.get("transcript_path", "not provided")
    lines.append(f"- transcript_path: {transcript_path}")

    # Session ID (derived from transcript_path if possible)
    if transcript_path and transcript_path != "not provided":
        session_id = Path(transcript_path).stem[:16]
    else:
        session_id = "not provided"
    lines.append(f"- session_id: {session_id}")

    # Session start
    session_start = payload.get("session_start", "not provided")
    lines.append(f"- session_start: {session_start}")

    # Model
    model = payload.get("model", {})
    model_name = model.get("display_name", "not provided") if isinstance(model, dict) else "not provided"
    lines.append(f"- model: {model_name}")

    # Effort level
    effort = payload.get("effort", "not provided")
    lines.append(f"- effort: {effort}")

    # CWD
    cwd = payload.get("cwd", "not provided")
    lines.append(f"- cwd: {cwd}")

    # Context window
    context_window = payload.get("context_window", {})
    if context_window:
        current_usage = context_window.get("current_usage", {})
        lines.append(f"- input_tokens: {current_usage.get('input_tokens', 'not provided')}")
        lines.append(f"- output_tokens: {current_usage.get('output_tokens', 'not provided')}")
        lines.append(f"- cache_creation_tokens: {current_usage.get('cache_creation_tokens', 'not provided')}")
        lines.append(f"- cache_read_tokens: {current_usage.get('cache_read_tokens', 'not provided')}")

        context_size = context_window.get("context_window_size", 0)
        current_tokens = current_usage.get("input_tokens", 0)
        if context_size > 0:
            percent = round(current_tokens / context_size * 100, 1)
            lines.append(f"- context_percent: {percent}%")
        else:
            lines.append("- context_percent: not provided")
    else:
        lines.append("- context_percent: not provided")

    # Compact trigger info
    lines.append(f"- compact_trigger: {payload.get('compact_trigger', 'not provided')}")

    # Rate limits (if present)
    rate_limits = payload.get("rate_limits", {})
    if rate_limits:
        five_hour = rate_limits.get("five_hour", {})
        seven_day = rate_limits.get("seven_day", {})
        if five_hour:
            lines.append(f"- usage_5h_percent: {five_hour.get('used_percentage', 'not provided')}")
        if seven_day:
            lines.append(f"- usage_7d_percent: {seven_day.get('used_percentage', 'not provided')}")

    lines.append("")
    lines.append("*Snapshot generated by PreCompact hook*")

    return lines


def write_snapshot(content_lines: list, output_dir: str, dry_run: bool = False) -> str:
    """Write snapshot file and return path."""
    os.makedirs(output_dir, exist_ok=True)
    timestamp = format_timestamp()
    filename = f"{timestamp}_precompact-snapshot.md"
    filepath = os.path.join(output_dir, filename)

    if dry_run:
        return filepath

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            # Write frontmatter
            f.write("---\n")
            f.write(f"name: precompact-{timestamp}\n")
            f.write("type: precompact_snapshot\n")
            f.write("source: hook\n")
            f.write("default_load: false\n")
            f.write("status: unreviewed\n")
            f.write("promote_requires_user_approval: true\n")
            f.write("---\n\n")
            # Write content
            for line in content_lines:
                f.write(line + "\n")
    except Exception as e:
        sys.stderr.write(f"err:io\n")
        sys.exit(0)  # Silent exit, don't block compact

    return filepath


def main():
    """Main entry point."""
    dry_run = "--dry-run" in sys.argv
    memory_dir = DEFAULT_MEMORY_DIR
    output_dir = DEFAULT_OUTPUT_DIR

    for i, arg in enumerate(sys.argv):
        if arg == "--memory-dir" and i + 1 < len(sys.argv):
            memory_dir = sys.argv[i + 1]
        if arg == "--output-dir" and i + 1 < len(sys.argv):
            output_dir = sys.argv[i + 1]

    # Read stdin
    payload = read_stdin()

    # Handle invalid JSON
    if payload is None:
        sys.stderr.write(f"err:io\n")
        sys.exit(0)  # Silent exit on parse error

    # Generate content
    content_lines = generate_snapshot_content(payload)

    # Check line limit
    if len(content_lines) > 80:
        sys.stderr.write(f"err:io\n")
        sys.exit(0)

    # Write snapshot
    if dry_run:
        filepath = os.path.join(output_dir, f"{format_timestamp()}_precompact-snapshot.md")
        print(f"[dry-run] would write: {filepath}")
        print(f"[dry-run] frontmatter: type=precompact_snapshot, status=unreviewed")
        print(f"[dry-run] content lines: {len(content_lines)}")
    else:
        write_snapshot(content_lines, output_dir, dry_run)


if __name__ == "__main__":
    main()